### ISSUE TITLE
Broadcast message not being received 

### ISSUE THREAD

**Issue by tusharbhatta** [bsorrentino/cordova-broadcaster#3]
Is this plugin working at all ? I am trying this in an ionic app like below but not able to make it work :

Here is my code inside app.js's $ionicPlatform.ready function :

if (window.broadcaster) {
        window.broadcaster.addEventListener( "CUSTOM_EVENT_NAME_BROADCASTED_FROM_NATIVE_LAYER", function( e ) {
                console.log( "Event received! userInfo: " + JSON.stringify(e)  );
        });            
} else {
        console.log('windown.broadcaster not available');
}

It's not invoking the else block, and the registered callback-block is not called also.

Any pointer would be helpful.

Thanks
- Tushar

**Comment by bsorrentino** [comment]
Hi Tushar

The plugin should work. I use it in my app

Please could you share some infos?
* Which platform
* cordova config.xml

**Comment by bsorrentino** [comment]
Hi Tushar

Probably I've identified problem. It is related only to IOS platform and concern the **cordova engine compatibility** 

In ```plugin.xml``` you have **version >= 4.0.0**
```xml
   <engines>
      <engine name="cordova" version=">=4.0.0" />
    </engines>
```

It is enough downgrade it at **3.9.1**

```xml
   <engines>
      <engine name="cordova" version=">=3.9.1" />
    </engines>
```
and perform

```
$ cordova platform rm ios
$ cordova platform add ios
```

However i've just deployed a new version **2.0.2** with such fix

Let me know

Regards,
Bartolo

**Comment by tusharbhatta** [comment]
Hi Bartolo,

Thanks for your reply. I'm trying on android and the problem persists after updating to your latest 2.0.2 (not required for my case as I'm using android version of the plugin).

Here are few more details :

Platform: Android, 
Test-device OS: 5.0.1 (lollipop)


### Usage Code:

```javascript

angular.module('starter', ['ionic'])
.run(function($ionicPlatform) {
    $ionicPlatform.ready(function() {
        // Hide the accessory bar by default (remove this to show the accessory bar above the keyboard
        // for form inputs)
        if (window.cordova && window.cordova.plugins && window.cordova.plugins.Keyboard) {
            cordova.plugins.Keyboard.hideKeyboardAccessoryBar(true);
        }
        if (window.StatusBar) {
            // org.apache.cordova.statusbar required
            StatusBar.styleLightContent();
        }

        if (window.broadcaster) {
            window.broadcaster.addEventListener( "com.ideacrest.sortify.core.broadcast.SMS_CLASSIFIED", function( e ) {
                    //log: didShow received! userInfo: {"data":"test"} 
                    console.log( "event received! userInfo: " + JSON.stringify(e)  );
            });
      
        }else {
            console.log('windown.broadcaster not available');
        }

    });
})
```

### Cordova config.xml :

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<widget id="com.ideacrest.sortify" version="0.0.1" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
  <name>Sortify</name>
  <description>
        An Ionic Framework and Cordova project.
    </description>
  <author email="hi@ionicframework" href="http://ionicframework.com/">
      Ionic Framework Team
    </author>
  <content src="index.html"/>
  <access origin="*"/>
  <preference name="webviewbounce" value="false"/>
  <preference name="UIWebViewBounce" value="false"/>
  <preference name="DisallowOverscroll" value="true"/>
  <preference name="android-minSdkVersion" value="16"/>
  <preference name="BackupWebStorage" value="none"/>
  <preference name="SplashScreen" value="screen"/>
  <preference name="SplashScreenDelay" value="3000"/>
  <feature name="StatusBar">
    <param name="ios-package" value="CDVStatusBar" onload="true"/>
  </feature>
  <platform name="android">
    <icon src="resources/android/icon/drawable-ldpi-icon.png" density="ldpi"/>
    <icon src="resources/android/icon/drawable-mdpi-icon.png" density="mdpi"/>
    <icon src="resources/android/icon/drawable-hdpi-icon.png" density="hdpi"/>
    <icon src="resources/android/icon/drawable-xhdpi-icon.png" density="xhdpi"/>
    <icon src="resources/android/icon/drawable-xxhdpi-icon.png" density="xxhdpi"/>
    <icon src="resources/android/icon/drawable-xxxhdpi-icon.png" density="xxxhdpi"/>
    <splash src="resources/android/splash/drawable-land-ldpi-screen.png" density="land-ldpi"/>
    <splash src="resources/android/splash/drawable-land-mdpi-screen.png" density="land-mdpi"/>
    <splash src="resources/android/splash/drawable-land-hdpi-screen.png" density="land-hdpi"/>
    <splash src="resources/android/splash/drawable-land-xhdpi-screen.png" density="land-xhdpi"/>
    <splash src="resources/android/splash/drawable-land-xxhdpi-screen.png" density="land-xxhdpi"/>
    <splash src="resources/android/splash/drawable-land-xxxhdpi-screen.png" density="land-xxxhdpi"/>
    <splash src="resources/android/splash/drawable-port-ldpi-screen.png" density="port-ldpi"/>
    <splash src="resources/android/splash/drawable-port-mdpi-screen.png" density="port-mdpi"/>
    <splash src="resources/android/splash/drawable-port-hdpi-screen.png" density="port-hdpi"/>
    <splash src="resources/android/splash/drawable-port-xhdpi-screen.png" density="port-xhdpi"/>
    <splash src="resources/android/splash/drawable-port-xxhdpi-screen.png" density="port-xxhdpi"/>
    <splash src="resources/android/splash/drawable-port-xxxhdpi-screen.png" density="port-xxxhdpi"/>
  </platform>
</widget>
```

I'm not sure what am I missing ? I feel the extra jar classes have some incompatibility (may be).

Please let me know if you find what the problem is. If you need some more details, please let me know also.

**Comment by tusharbhatta** [comment]
Got it working ... partially ... the problem was in the way another plugin broadcasting which CDVBroadcaster was listening to.

Now I'm having a crash from the CDVBroadcaster.java after receiving the broadcast :

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.os.Bundle.getString(java.lang.String, java.lang.String)' on a null object reference
10-26 17:26:03.337 E/AndroidRuntime(17783): 	at org.bsc.cordova.CDVBroadcaster$2.onReceive(CDVBroadcaster.java:153)
10-26 17:26:03.337 E/AndroidRuntime(17783): 	at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:297)
```

**Comment by tusharbhatta** [comment]
Hi Bartolo,

I have fixed the android crash issue upon receiving the broadcast by adding a check for the 'null' object as some broadcast intent may not have any extra information, which was the case for my crash. I have made a pull request with that simple check for your consideration. 

Thanks
- Tushar

**Comment by bsorrentino** [comment]
Thanks 

I'll merge it soon

**Comment by bsorrentino** [comment]
merged and released to 2.0.3
