### ISSUE TITLE
Send JSONObject as Bundle not working for Android

### ISSUE THREAD

**Issue by alejouribesanchez** [bsorrentino/cordova-broadcaster#47]
I want to send a simple JSON object but the plugin was not able to convert it correctly to JSON

I want to send this simple JSON
`{ 
   "data":{ 
      "testingkey":"testingValue"
   }
}`

So according to the documentation should be something like this
```
val bundle1 = Bundle()
bundle1.putString("testingkey", "testingValue")
val bundle2 = Bundle()
bundle2.putBundle("json", bundle1)
intent.putExtra("data",  bundle2)
```

After that in the listener when I put the log to see the response 
`console.log(JSON.stringify(e, null, "\t"))`

I got this:
`{
    	"isTrusted": false,
    	"data": "Bundle[{json=Bundle[{TestingKey=TestingValue}]}]"
    }`

Note that I don't want to send the JSON as string because if I try something like this:

`intent.putExtra("data",  jsont.toString())`

I got this:
```
{ 
   "data":"{\"testingkey\":\"testingValue\"}"
}
```
So it appears that your plugin is supporting just one depth in the JSON Object

**Comment by bsorrentino** [comment]
hi @alejouribesanchez 

The plugin essentialy allows strings exchange, so I think that JSON should be considered a convention in your software.

You states:

> Note that I don't want to send the JSON as string because if I try something like this:
`intent.putExtra("data", jsont.toString())`
> I got this:
> ```json
> { 
>   "data":"{\"testingkey\":\"testingValue\"}"
> }
> ```
> So it appears that your plugin is supporting just one depth in the JSON Object

But you can simply parse value of `data`  (based on convention)  using `JSON.parse` 

```javascript
var jsonObject = JSON.parse( eventResut.data );
```

What do you think about ?

**Comment by alejouribesanchez** [comment]
Hi @bsorrentino thanks for your answer, I understand that I can use
 `var jsonObject = JSON.parse( eventResult.data );` and that's exactly what I am doing.
But this is not consistent with the iOS version, because in iOS when I put the same information inside an NSDictionary, the iOS plugin is able to convert that information to a JSON object, So I am getting two different outputs, one for android and another for iOS. So it would be great if the plugin is consistent across platforms

**Comment by bsorrentino** [comment]
> So it would be great if the plugin is consistent across platforms
It must be, I'll work on

**Comment by bsorrentino** [comment]
fix released in [4.0.0](https://github.com/bsorrentino/cordova-broadcaster/releases/tag/v4.0.0)

**Comment by alejouribesanchez** [comment]
> fix released in [4.0.0](https://github.com/bsorrentino/cordova-broadcaster/releases/tag/v4.0.0)

I've just tested and it's working perfect thanks!

**Comment by alejouribesanchez** [comment]
Hi @bsorrentino There is something still not working in the released 4.0.0 The android Json is introducing some weird keys. 
This is how looks Android
![Android](https://user-images.githubusercontent.com/3950665/69998463-59557480-1524-11ea-9627-3d1fa8964aeb.png)

This how looks iOS
![iOS](https://user-images.githubusercontent.com/3950665/69998481-6a9e8100-1524-11ea-9296-a0ebd2e7e8c1.png)

**Comment by bsorrentino** [comment]
Hi @alejouribesanchez 

Thanks for feedback ... I’ll working on asap

Please consider to open a new issue so you help me to manage projects releases

Thx in advance

**Comment by alejouribesanchez** [comment]
Thanks this is the new issue https://github.com/bsorrentino/cordova-broadcaster/issues/48
